### ISSUE TITLE
import ensembl genomes for Drosophila ananassae, mojavensis, pseudoobscura, simulans, virilis and yakuba

### ISSUE THREAD

**Issue by sfexova** [gxa/atlas-annotations#35]
Genomes for all these available in EnsemblMetazoa (http://metazoa.ensembl.org/biomart/martview/e5f7c91d34e0866ca19fbd37ee50e394)

**Comment by pcm32** [comment]
Do we need them all? The process of E! Update is intensive on a per organism level (we need to curate mappings of fields per organism), so adding each new species is time consuming and potentially adds load for every subsequent release. Do we need them all for pending studies or just some of these?

These species don't seem to be in the list of excluded species for biomart, so should be fine:

https://github.com/Ensembl/ensembl-biomart/blob/release/99/scripts/exclude_vertebrates.ini

(there doesn't seem to be an invertebrate exclude).

Let me know, as I'm starting the process to move to E! 99, thanks

**Comment by pcm32** [comment]
These had been added through #39, will close this, thanks @sfexova
